#!/bin/sh

# This script is provided for backward compatibility with programs
# that use pspell.  Do not use as it will eventually go away.

case $1 in
--version | version)
  echo 0.60.6.1
  ;;
--datadir | datadir)
  echo "/home/expertiza_developer/heroku-buildpack-aspell/aspell/share"
  ;;
--pkgdatadir | pkgdatadir)
  echo "/home/expertiza_developer/heroku-buildpack-aspell/aspell/lib/aspell-0.60"
  ;;
*)
  echo "usage: pspell-config version|datadir|pkgdatadir"
  ;;
esac
